// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCapHJlugGzabsNDRE8Y4n3cy1QaUMuQ5c',
    appId: '1:188801396370:android:fe6d42b67a3df413df004b',
    messagingSenderId: '188801396370',
    projectId: 'sleepdoctor-7271a',
    storageBucket: 'sleepdoctor-7271a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClGey856XGC8KnF5Nv_uP0H4jR4xsKVLs',
    appId: '1:188801396370:ios:939d0ec03e3cef78df004b',
    messagingSenderId: '188801396370',
    projectId: 'sleepdoctor-7271a',
    storageBucket: 'sleepdoctor-7271a.firebasestorage.app',
    iosClientId: '188801396370-4evs1l3n1foqq251038u4tv8cs18q0r1.apps.googleusercontent.com',
    iosBundleId: 'com.sleepdoctor.sleepDoctor',
  );
}
